### ISSUE TITLE
"error: Invalid value" on OSX Catalina

### ISSUE THREAD

**Issue by Algiane** [parcoach/parcoach#1]
Hi Emmanuelle,

Thank you for this application that seems promising. I am interested to improve the robustness of my MPI code with it.

It builds smoothly both on OSX and ubuntu but I have different issues trying to execute the static analysis (I will create another issue for ubuntu).

On Catalina, I didn't succeed to run the provided tests. I try to run the following command:
```shell
 opt -load libaSSA.so -parcoach -check-mpi < noerror2.bc
```
I get the following error:
`error: Invalid value (Producer: 'APPLE_1_1100.0.33.17_0' Reader: 'LLVM 3.9.1')`

Parcoach is built with clang-11 (coming with XCode) and llvm-3.9.1.

Do you have any idea of what may cause this error?

Thank you by advance,
Algiane

**Comment by esaillar** [comment]
Hi Algiane,

Sorry for the delay. Parcoach now works with LLVM 9. LLVM 3.9 was old and I also add troubles with clang-11. May I suggest you try the new release?

Thank you,
Emmanuelle

**Comment by Algiane** [comment]
Hi Emmanuelle,

Thank you for your reply, I will try as soon as possible.

Regards,
Algiane
