### ISSUE TITLE
opt: expected top-level entity on ubuntu

### ISSUE THREAD

**Issue by Algiane** [parcoach/parcoach#2]
Hello,

I can run successfully the test cases provided by parcoach on unbuntu 16.04 so my questions are more linked to the `opt` command and to compiler flags than to parcoach.

When I try to run parcoach on my application  I get an error from `opt`:
```
opt: bin/parmmg_debug:1:1: error: expected top-level entity
```

I try to build my application first with the `-flto` compiler flag (as said in the parcoach readme) then with the `-emit-llvm` flag (as done for the parcoach tests) then with both flags without success. 

Thank you by advance for your help.

Regards,
Algiane

**Comment by esaillar** [comment]
Hello Algiane,

Did you try to run Parcoach on a single file first? Here is the command to use:

clang -c -g -emit-llvm myprogram.c
opt -load path/to/parcoachlib/aSSA.* -parcoach -check-mpi < myprogram.bc  > /dev/null

Note that you can now run ctest in your build directory to test Parcoach. 

Let me know if you still have troubles.
Regards,
Emmanuelle

**Comment by Algiane** [comment]
Hi Emmanuelle,

Thanks for the tips.

Regards,
Algiane
